Defaults.containerTag = "latest"
Defaults.Port = 80
Defaults.dataContents = "[Volume]"
Secrets = ["domain"]

[[Services]]
Service = "freshrss.service"
RestartedBy = ["freshrss.container", "freshrss.env"]
